name: "Foundry VTT Pf2e module"
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3

    - name: Substitute Manifest and Download Links For Versioned Ones
      id: sub_manifest_link_version
      uses: microsoft/variable-substitution@v1
      with:
        files: 'module.json'
      env:
        version: ${{github.event.release.tag_name}}
        url: https://github.com/${{github.repository}}
        manifest: https://github.com/${{github.repository}}/releases/latest/download/module.json
        download: https://github.com/${{github.repository}}/releases/latest/download/pf2e-export-scribe.zip

    - name: Zip files
      uses: thedoctor0/zip-release@0.7.1
      with:
        type: 'zip'
        filename: 'pf2e-export-scribe.zip'
        exclusions: '*.git* .vscode'

    - name: Create Version Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ env.systemVersion }}
        allowUpdates: false
        draft: false
        prerelease: false
        artifacts: "module.json,pf2e-export-scribe.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.systemVersion }}

