name: Release

on:
  workflow_dispatch:

env:
  fvtt_minimum: 11
  fvtt_verified: 11
  fvtt_dry_run: true

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Submit package to FoundryVTT Package Release API
        run: |
          curl -X POST "https://api.foundryvtt.com/_api/packages/release_version/" \
            -H "Content-Type: application/json" \
            -H "Authorization: ${{ secrets.FOUNDRYVTT_RELEASE_TOKEN }}" \
            -d '{
              "id": "${{ needs.build.outputs.id }}",
              "dry-run": ${{ env.fvtt_dry_run }},
              "release": {
                "version": "${{ env.systemVersion }}",
                "manifest": "https://github.com/${{ github.repository }}/releases/download/${{ env.systemVersion }}/module.json",
                "notes": "https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md",
                "compatibility": {
                  "minimum": "${{ env.fvtt_minimum }}",
                  "verified": "${{ env.fvtt_verified }}"
                }
              }
            }'